# Generated by Django 4.2 on 2023-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Describe yourself here'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.CharField(default='Stack', max_length=100),
        ),
    ]
