# Generated by Django 4.2 on 2023-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='images/default.jpg', upload_to='post_image/'),
        ),
    ]
